### ISSUE TITLE
Suggestion to alias format checking

### ISSUE THREAD

**Issue by tkasukawa** [ddbj/submission-excel2xml#2]
Currently, experiment and run aliases should be in "Experiment-\d+" and "Run-\d+", respectively.
If a user wrote texts in the incorrect format (e.g. Experiment_0001), the system ignore them.
However, in this case, the system does not show any errors and warnings, and produces blank XML files.
For users, it is not easy to recognize why this happens.

Thus, I suggest to put error or warning messages for the incorrect alias texts.

**Comment by komstat** [comment]
Sorry for my late response. I added warning for invalid alias formats. [diff](https://github.com/ddbj/submission-excel2xml/commit/23c22efd5938fa8518362780fe1dd6e4c1beda45)
